#!/usr/bin/env node
/**
 * Regenerates supabase/seed.sql from src/data/catalog.json, so the catalogue in
 * the database always matches the one the app ships with.
 *
 *   npm run seed
 */

import { readFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const catalog = JSON.parse(
  await readFile(path.join(process.cwd(), "src/data/catalog.json"), "utf8"),
);

const quote = (value) => `'${String(value).replace(/'/g, "''")}'`;
const nullable = (value) => (value === undefined || value === null ? "null" : String(value));

const lines = [
  "-- Generated by supabase/generate-seed.mjs — do not edit by hand.",
  "-- Run after the migrations to fill the catalogue.",
  "",
  "insert into public.categories (id, title_uk, title_en, blurb_uk, blurb_en, icon, accent, sort_order) values",
  catalog.categories
    .map((category, index) =>
      `  (${[
        quote(category.id),
        quote(category.title.uk),
        quote(category.title.en),
        quote(category.blurb?.uk ?? ""),
        quote(category.blurb?.en ?? ""),
        quote(category.icon ?? "🧩"),
        quote(category.accent ?? "mint"),
        String(index),
      ].join(", ")})`,
    )
    .join(",\n") + "\non conflict (id) do update set",
  [
    "  title_uk = excluded.title_uk",
    "  title_en = excluded.title_en",
    "  blurb_uk = excluded.blurb_uk",
    "  blurb_en = excluded.blurb_en",
    "  icon = excluded.icon",
    "  accent = excluded.accent",
    "  sort_order = excluded.sort_order",
  ].join(",\n") + ";",
  "",
  "insert into public.puzzles (id, category_id, title_uk, title_en, image, width, height, access, points_cost, price_cents, license, sort_order) values",
  catalog.puzzles
    .map((puzzle, index) =>
      `  (${[
        quote(puzzle.id),
        quote(puzzle.categoryId),
        quote(puzzle.title.uk),
        quote(puzzle.title.en),
        quote(puzzle.image),
        String(puzzle.width),
        String(puzzle.height),
        quote(puzzle.access),
        nullable(puzzle.pointsCost),
        nullable(puzzle.priceCents),
        quote(puzzle.license ?? "demo"),
        String(index),
      ].join(", ")})`,
    )
    .join(",\n") + "\non conflict (id) do update set",
  [
    "  category_id = excluded.category_id",
    "  title_uk = excluded.title_uk",
    "  title_en = excluded.title_en",
    "  image = excluded.image",
    "  width = excluded.width",
    "  height = excluded.height",
    "  access = excluded.access",
    "  points_cost = excluded.points_cost",
    "  price_cents = excluded.price_cents",
    "  license = excluded.license",
    "  sort_order = excluded.sort_order",
  ].join(",\n") + ";",
  "",
];

process.stdout.write(lines.join("\n"));
