/**
 * Regenerates supabase/seed.sql from src/data/catalog.ts, so the catalogue in
 * the database always matches the one the app ships with.
 *
 *   node supabase/generate-seed.mts > supabase/seed.sql
 */

import { categories, puzzles } from "../src/data/catalog.ts";

const quote = (value: string) => `'${value.replace(/'/g, "''")}'`;
const nullable = (value: number | undefined) => (value === undefined ? "null" : String(value));

const lines: string[] = [
  "-- Generated by supabase/generate-seed.mts — do not edit by hand.",
  "-- Run after 0001_init.sql to fill the catalogue.",
  "",
  "insert into public.categories (id, title_uk, title_en, blurb_uk, blurb_en, icon, accent, sort_order) values",
];

lines.push(
  categories
    .map((category, index) =>
      `  (${[
        quote(category.id),
        quote(category.title.uk),
        quote(category.title.en),
        quote(category.blurb.uk),
        quote(category.blurb.en),
        quote(category.icon),
        quote(category.accent),
        String(index),
      ].join(", ")})`,
    )
    .join(",\n") + "\non conflict (id) do update set",
);

lines.push(
  [
    "  title_uk = excluded.title_uk",
    "  title_en = excluded.title_en",
    "  blurb_uk = excluded.blurb_uk",
    "  blurb_en = excluded.blurb_en",
    "  icon = excluded.icon",
    "  accent = excluded.accent",
    "  sort_order = excluded.sort_order",
  ].join(",\n") + ";",
  "",
  "insert into public.puzzles (id, category_id, title_uk, title_en, image, width, height, access, points_cost, price_cents, license, sort_order) values",
);

lines.push(
  puzzles
    .map((puzzle, index) =>
      `  (${[
        quote(puzzle.id),
        quote(puzzle.categoryId),
        quote(puzzle.title.uk),
        quote(puzzle.title.en),
        quote(puzzle.image),
        String(puzzle.width),
        String(puzzle.height),
        quote(puzzle.access),
        nullable(puzzle.pointsCost),
        nullable(puzzle.priceCents),
        quote("demo"),
        String(index),
      ].join(", ")})`,
    )
    .join(",\n") + "\non conflict (id) do update set",
);

lines.push(
  [
    "  category_id = excluded.category_id",
    "  title_uk = excluded.title_uk",
    "  title_en = excluded.title_en",
    "  image = excluded.image",
    "  access = excluded.access",
    "  points_cost = excluded.points_cost",
    "  price_cents = excluded.price_cents",
    "  sort_order = excluded.sort_order",
  ].join(",\n") + ";",
  "",
);

process.stdout.write(lines.join("\n"));
