-- Generated by supabase/generate-seed.mts — do not edit by hand.
-- Run after 0001_init.sql to fill the catalogue.

insert into public.categories (id, title_uk, title_en, blurb_uk, blurb_en, icon, accent, sort_order) values
  ('nature', 'Природа', 'Nature', 'Поля, квіти й тепле світло', 'Fields, flowers and warm light', '🌿', 'mint', 0),
  ('water', 'Вода', 'Water', 'Море, озера й краплі', 'Seas, lakes and droplets', '🌊', 'sky', 1),
  ('mountains', 'Гори і небо', 'Peaks & sky', 'Туман, зорі та висота', 'Mist, stars and altitude', '🏔️', 'lilac', 2),
  ('city', 'Місто і ретро', 'City & retro', 'Вулиці, авто й вогні', 'Streets, cars and lights', '🚗', 'peach', 3)
on conflict (id) do update set
  title_uk = excluded.title_uk,
  title_en = excluded.title_en,
  blurb_uk = excluded.blurb_uk,
  blurb_en = excluded.blurb_en,
  icon = excluded.icon,
  accent = excluded.accent,
  sort_order = excluded.sort_order;

insert into public.puzzles (id, category_id, title_uk, title_en, image, width, height, access, points_cost, price_cents, license, sort_order) values
  ('nature-blossom', 'nature', 'Весняне цвітіння', 'Spring blossom', '/puzzles/106.jpg', 1200, 900, 'free', null, null, 'demo', 0),
  ('nature-green-field', 'nature', 'Зелене поле', 'Green field', '/puzzles/107.jpg', 1200, 900, 'free', null, null, 'demo', 1),
  ('nature-garden', 'nature', 'Літній сад', 'Summer garden', '/puzzles/127.jpg', 1200, 900, 'free', null, null, 'demo', 2),
  ('nature-berries', 'nature', 'Малина на столі', 'Berries on the table', '/puzzles/102.jpg', 1200, 900, 'points', 150, null, 'demo', 3),
  ('nature-morning', 'nature', 'Ранкова трава', 'Morning grass', '/puzzles/109.jpg', 1200, 900, 'points', 200, null, 'demo', 4),
  ('nature-sunset', 'nature', 'Захід над полем', 'Sunset over the field', '/puzzles/110.jpg', 1200, 900, 'points', 260, null, 'demo', 5),
  ('nature-wheat', 'nature', 'Колоски', 'Wheat ears', '/puzzles/112.jpg', 1200, 900, 'points', 320, null, 'demo', 6),
  ('nature-tuscany', 'nature', 'Тосканська дорога', 'Tuscan road', '/puzzles/116.jpg', 1200, 900, 'paid', null, 125, 'demo', 7),
  ('nature-sunflower', 'nature', 'Соняшник', 'Sunflower', '/puzzles/118.jpg', 1200, 900, 'paid', null, 125, 'demo', 8),
  ('water-turquoise', 'water', 'Бірюзове море', 'Turquoise sea', '/puzzles/124.jpg', 1200, 900, 'free', null, null, 'demo', 9),
  ('water-horizon', 'water', 'Тиха гладь', 'Calm horizon', '/puzzles/135.jpg', 1200, 900, 'free', null, null, 'demo', 10),
  ('water-waves', 'water', 'Хвилі', 'Waves', '/puzzles/126.jpg', 1200, 900, 'points', 150, null, 'demo', 11),
  ('water-flight', 'water', 'Політ над морем', 'Flight over the sea', '/puzzles/130.jpg', 1200, 900, 'points', 220, null, 'demo', 12),
  ('water-droplets', 'water', 'Краплі', 'Droplets', '/puzzles/123.jpg', 1200, 900, 'points', 280, null, 'demo', 13),
  ('water-lake', 'water', 'Озеро в горах', 'Mountain lake', '/puzzles/128.jpg', 1200, 900, 'points', 340, null, 'demo', 14),
  ('water-rocky', 'water', 'Скелястий берег', 'Rocky shore', '/puzzles/132.jpg', 1200, 900, 'paid', null, 125, 'demo', 15),
  ('water-shell', 'water', 'Мушля', 'Seashell', '/puzzles/139.jpg', 1200, 900, 'paid', null, 125, 'demo', 16),
  ('mountains-misty', 'mountains', 'Туманні пагорби', 'Misty hills', '/puzzles/114.jpg', 1200, 900, 'free', null, null, 'demo', 17),
  ('mountains-fog', 'mountains', 'Гірський туман', 'Mountain fog', '/puzzles/121.jpg', 1200, 900, 'free', null, null, 'demo', 18),
  ('mountains-shore', 'mountains', 'Береги озера', 'Lake shores', '/puzzles/125.jpg', 1200, 900, 'points', 160, null, 'demo', 19),
  ('mountains-stone', 'mountains', 'Камʼяні велетні', 'Stone giants', '/puzzles/136.jpg', 1200, 900, 'points', 230, null, 'demo', 20),
  ('mountains-stars', 'mountains', 'Зоряна ніч', 'Starry night', '/puzzles/120.jpg', 1200, 900, 'points', 300, null, 'demo', 21),
  ('mountains-palm', 'mountains', 'Пальма на світанку', 'Palm at dawn', '/puzzles/108.jpg', 1200, 900, 'points', 360, null, 'demo', 22),
  ('mountains-ice', 'mountains', 'Крижані краплі', 'Frozen drops', '/puzzles/115.jpg', 1200, 900, 'paid', null, 125, 'demo', 23),
  ('mountains-blue', 'mountains', 'Синій вітер', 'Blue wind', '/puzzles/113.jpg', 1200, 900, 'paid', null, 125, 'demo', 24),
  ('city-retro-car', 'city', 'Ретро авто', 'Retro car', '/puzzles/133.jpg', 1200, 900, 'free', null, null, 'demo', 25),
  ('city-pickup', 'city', 'Старий пікап', 'Old pickup', '/puzzles/111.jpg', 1200, 900, 'free', null, null, 'demo', 26),
  ('city-bridge', 'city', 'Міст уночі', 'Bridge at night', '/puzzles/122.jpg', 1200, 900, 'points', 170, null, 'demo', 27),
  ('city-arch', 'city', 'Дерев''яна арка', 'Wooden arch', '/puzzles/134.jpg', 1200, 900, 'points', 240, null, 'demo', 28),
  ('city-dreamcatcher', 'city', 'Ловець снів', 'Dreamcatcher', '/puzzles/104.jpg', 1200, 900, 'points', 300, null, 'demo', 29),
  ('city-crowd', 'city', 'Вогні концерту', 'Concert lights', '/puzzles/117.jpg', 1200, 900, 'points', 380, null, 'demo', 30),
  ('city-bench', 'city', 'На лавці', 'On the bench', '/puzzles/129.jpg', 1200, 900, 'paid', null, 125, 'demo', 31),
  ('city-tunnel', 'city', 'Світло в тунелі', 'Light in the tunnel', '/puzzles/137.jpg', 1200, 900, 'paid', null, 125, 'demo', 32)
on conflict (id) do update set
  category_id = excluded.category_id,
  title_uk = excluded.title_uk,
  title_en = excluded.title_en,
  image = excluded.image,
  access = excluded.access,
  points_cost = excluded.points_cost,
  price_cents = excluded.price_cents,
  sort_order = excluded.sort_order;
